### ISSUE TITLE
Configurable product swatch selection for the first time takes longer

### ISSUE THREAD

**Issue by VivekShingala** [magesuite/magepack#56]
Hi

Thank you very much for this wonderful extension. It has improved the speed of our store a lot.

However, after enabling magepack bundling we are facing an issue with our configurable products. When the product page is loaded and we click on one of the swatches, it takes more time to actually select that swatch. It works fine for any subsequent selection.

![Configurable product swatch selection for the first time takes longer](https://media.giphy.com/media/TrG2rJvkK6eAjzb2ha/giphy.gif)

**Comment by krzksz** [comment]
Hey @VivekShingala! It's great to hear that Magepack is useful for you.

As to your bug report - I have never encountered such issue so I would like to ask you to either try to debug it yourself using devtools or give an example URL when we can debug it.

**Comment by VivekShingala** [comment]
Hi @krzksz 

Sure, this is the product url you may use to debug.
Link: https://bit.ly/34UL4e4

Thanks

**Comment by krzksz** [comment]
Hey @VivekShingala, I'm closing this as not related to Magepack because it's Magesuite issue 😄

First of all, please make sure to update to this version of: https://github.com/magesuite/performance-product/releases/tag/v1.2.3 which fixes incorrect fetching of async prices on PDP + make sure you have varnish set up because it shouldn't take so much time to return them once they are in cache.

**Comment by VivekShingala** [comment]
Thanks @krzksz 

Disabling magesuite/performance package did the trick. We are not using Varnish yet. I will test the module again when we will setup varnish on our server. 

Thanks again. It helped a lot.
